import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1b",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c6",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "on-primary-container": "#848484",
        "inverse-primary": "#c6c6c6",
        secondary: "#5e5e5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e1dfdf",
        "on-secondary-container": "#626262",
        "secondary-fixed": "#e4e2e2",
        "secondary-fixed-dim": "#c7c6c6",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#464747",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1a1c1c",
        "on-tertiary-container": "#838484",
        "tertiary-fixed": "#e3e2e2",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#464747",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        surface: "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#4c4546",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "surface-tint": "#5e5e5e",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        outline: "#7e7576",
        "outline-variant": "#cfc4c5",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "stack-xl": "80px",
        "margin-desktop": "80px",
        "gutter-desktop": "32px",
      },
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
