import { NextResponse } from 'next/server'
import { createClient } from '@/utils/supabase/server'

/**
 * This route handles password recovery links generated by our custom email template.
 * The email link format is:
 *   /auth/reset-callback?token_hash=XXX&type=recovery
 *
 * token_hash is verified server-side via verifyOtp — it does NOT require a PKCE
 * verifier stored in the browser, so it works on any device and any browser.
 */
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)

  // Determine the base URL (handles Vercel's load balancer)
  const forwardedHost = request.headers.get('x-forwarded-host')
  const origin = new URL(request.url).origin
  const isLocalEnv = process.env.NODE_ENV === 'development'
  const baseUrl = isLocalEnv
    ? origin
    : forwardedHost
    ? `https://${forwardedHost}`
    : origin

  const token_hash = searchParams.get('token_hash')
  const type = searchParams.get('type')

  // token_hash flow (from our custom email template) — works cross-device/cross-browser
  if (token_hash && type === 'recovery') {
    const supabase = await createClient()
    const { error } = await supabase.auth.verifyOtp({
      token_hash,
      type: 'recovery',
    })

    if (!error) {
      // Session established — send user to change their password
      return NextResponse.redirect(`${baseUrl}/reset-password`)
    }

    console.error('[auth/reset-callback] verifyOtp error:', error.message)
    return NextResponse.redirect(`${baseUrl}/login?error=link_expired`)
  }

  // Fallback: PKCE code flow (older links)
  const code = searchParams.get('code')
  if (code) {
    const supabase = await createClient()
    const { error } = await supabase.auth.exchangeCodeForSession(code)
    if (!error) {
      return NextResponse.redirect(`${baseUrl}/reset-password`)
    }
    console.error('[auth/reset-callback] exchangeCodeForSession error:', error.message)
  }

  // Nothing worked
  return NextResponse.redirect(`${baseUrl}/login?error=invalid_link`)
}
